#!/bin/bash

# VIM
alias svim="sudoedit"

#LS
alias sl='ls'
alias l='ls'
alias t='tree'
alias ls="ls -hF --color=always"
alias ll='ls -lh'
alias la='ls -lah'              # list all
alias lx='ls -lXB'              # sort by extension
alias lk='ls -lSr'              # sort by size
alias lc='ls -lcr'              # sort by change time
alias lu='ls -lur'              # sort by access time
alias lr='ls -lR'               # recursive ls
alias lt='ls -ltr'              # sort by date

alias lz="ls -lh | awk '{print \$5, \$9}' | column -t"
alias lza="ls -lah | awk '{print \$5, \$9}' | column -t"

alias md="mkdir"
alias bd="cd -"

# OPEN
alias open='xdg-open'

# number of files in directory
alias nbf="ls | wc -l"
alias nbaf="ls -a | wc -l"

# updates
alias up='sudo apt-get update && sudo apt-get upgrade'
alias upgrade="sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y && sudo apt-get clean"

# show installed packages
alias listpackages='dpkg --get-selections'
alias showinstalled='listpackages | grep -v deinstall | grep '

# install
alias agi='sudo apt-get install'

# arch
alias pacS='sudo pacman -S'
alias pacR='sudo pacman -Rscn'
alias pacSyu='sudo pacman -Syu'

# Disk usage
alias dul="du -h --max-depth=1"

# parent directory
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

#alias ctar="tar czvf" # c: create zip, z:gzip mode (more compression), v: verbose, show files details, f: indicate the file to compress
#alias xtar="tar xvf" # x: extract zip

# zshrc
alias sz='source ~/.zshrc'
alias vz='vim ~/.zshrc'

# yolo
alias yolo='cat /dev/urandom | hexdump -C | grep "ca fe"'

# arxiv
alias arxiv='~/Documents/dev/arxiv/search-arxiv/arxiv.py'

# scan nmap
alias ip_scan='nmap -sP 192.168.1.0/24'
